In [2]:
# this part is super tricky, many many hours can be lost on searching errors if people are not aware of 
#shallow vs deep copy

In [3]:
#what you know so far:
a = 2
# = is "assignment operator", you already know it is NOT equal, and it works from left to righ,
#  b has now  value of a
b = a
#lets check
a, b

(2, 2)

In [4]:
# now i modify a:
a += 1
a

3

In [5]:
# will b change? or be same? Let's check:
b

2

In [6]:
# b did not change because assignment operator = between int types:
#(int) = (int) makes  DEEP COPY
# lets check one more thing:
id(a), id(b)

(140104539570480, 140104539570448)

In [ ]:
#as you can see both a and b are DIFFFERNT OBJECTS (of type int) with different referces

In [ ]:
#now things got different if we deal with matrices:

In [9]:
import numpy as np
a_matrix = np.ones((2, 2))
a_matrix

array([[1., 1.],
       [1., 1.]])

In [10]:
type(a_matrix)

numpy.ndarray

In [12]:
# now we assign value of a_matrix to b_matrix 
# note it is different because we have different types:
# numpy.ndarray = numpy.ndarray we assign between numpy array, still from left to right <-
b_matrix = a_matrix

In [14]:
# now, lets check something:
id(b_matrix), id(a_matrix)

(140103849556080, 140103849556080)

In [ ]:
# did you noticed id are same.... ? (compare to same thing we did with int)

In [17]:
#now, lets modify a
a_matrix[0,0] = 0
a_matrix

array([[0., 1.],
       [1., 1.]])

In [18]:
# lets check b:
b_matrix

array([[0., 1.],
       [1., 1.]])

In [ ]:
# b_matrix has changed tooo! its because this = assignment operator works different between big types like ndarray
# it actually makes a "shallow copy", so it only copies reference!

In [20]:
# now lets do something more:
c_matrix = a_matrix.copy()
c_matrix

array([[0., 1.],
       [1., 1.]])

In [21]:
# c_matrix still looks like a_matrix, lets compare references:
id(c_matrix), id(a_matrix)

(140103849829808, 140103849556080)

In [22]:
# probably you noticed references are different...
# now, lets modify a matrix
a_matrix[0,0] = 13
a_matrix

array([[13.,  1.],
       [ 1.,  1.]])

In [ ]:
# guess what will be value of c_matrix
c_matrix

In [23]:
# yes, c_matrix will not change, because we did a deep copy, so new object was created, and all values from
# a_matrix were copied, not just reference like in case of b_matrix

array([[0., 1.],
       [1., 1.]])