In [1]:
import numpy as np

In [2]:
L = 1
N = 10
x = np.linspace(0, L, N+1)
y = np.linspace(0, L, N+1)
xij, yij = np.meshgrid(x, y, indexing='ij')

In [3]:
yij[0]

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [7]:
type(yij[0])

numpy.ndarray

In [4]:
len(yij[0])

11

In [11]:
test = np.array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])
test

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [8]:
type(test)

numpy.ndarray

In [6]:
np.equal(yij[0], test)

array([ True,  True,  True, False,  True,  True, False, False,  True,
        True,  True])

In [14]:
indices = np.equal(yij[0], test)
np.where(indices == False)

(array([3, 6, 7]),)

In [15]:
yij[0][3], test[3], yij[0][3] == test[3],

(0.30000000000000004, 0.3, False)

In [16]:
yij[0][6]

0.6000000000000001

In [17]:
y[6]

0.6000000000000001